module.exports = {
  APP_ENDPOINT: 'X-WOPI-AppEndpoint',
  CLIENT_VERSION: 'X-WOPI-ClientVersion',
  CORRELATION_ID: 'X-WOPI-CorrelationId',
  DEVICE_ID: 'X-WOPI-DeviceId',
  SESSION_ID: 'X-WOPI-SessionId',
  MACHINE_NAME: 'X-WOPI-MachineName',
  PROOF: 'X-WOPI-Proof',
  PROOF_OLD: 'X-WOPI-ProofOld',
  TIMESTAMP: 'X-WOPI-TimeStamp',
  SESSION_CONTEXT: 'X-WOPI-SessionContext',
  URL_TYPE: 'X-WOPI-UrlType',
  MAX_EXPECTED_SIZE: 'X-WOPI-MaxExpectedSize',
  OLD_LOCK: 'X-WOPI-OldLock',
  OVERRIDE: 'X-WOPI-Override',
  HOST_ENDPOINT: 'X-WOPI-HostEndpoint',
  SERVER_ERROR: 'X-WOPI-ServerError',
  SERVER_VERSION: 'X-WOPI-ServerVersion',
  ITEM_VERSION: 'X-WOPI-ItemVersion',
  LOCK: 'X-WOPI-Lock',
  LOCK_FAILURE_REASON: 'X-WOPI-LockFailureReason'
};
