module.exports = {
  VIEW: 'view',
  EDIT: 'edit',
  EDITNEW: 'editnew',
  CONVERT: 'convert',
  GETINFO: 'getinfo',
  INTERACTIVEPREVIEW: 'interactivepreview',
  MOBILE_VIEW: 'mobileView',
  EMBEDVIEW: 'embedview',
  IMAGEPREVIEW: 'imagepreview',
  FORMSUBMIT: 'formsubmit',
  FORMEDIT: 'formedit',
  REST: 'rest',
  PRESENT: 'present',
  PRESENTSERVICE: 'presentservice',
  ATTEND: 'attend',
  ATTENDSERVICE: 'attendservice',
  PRELOADEDIT: 'preloadedit',
  PRELOADVIEW: 'preloadview',
  SYNDICATE: 'syndicate',
  LEGACYWEBSERVICE: 'legacywebservice',
  RTC: 'rtc',
  COLLAB: 'collab',
  DOCUMENTCHAT: 'documentchat'
};
