module.exports = {
  BUSINESS_USER: 'BUSINESS_USER',
  DC_LLCC: 'DC_LLCC',
  DISABLE_ASYNC: 'DISABLE_ASYNC',
  DISABLE_BROADCAST: 'DISABLE_BROADCAST',
  DISABLE_CHAT: 'DISABLE_CHAT',
  EMBEDDED: 'EMBEDDED',
  FULLSCREEN: 'FULLSCREEN',
  HOST_SESSION_ID: 'HOST_SESSION_ID',
  PERFSTATS: 'PERFSTATS',
  RECORDING: 'RECORDING',
  THEME_ID: 'THEME_ID',
  UI_LLCC: 'UI_LLCC',
  VALIDATOR_TEST_CATEGORY: 'VALIDATOR_TEST_CATEGORY'
};
